### ISSUE TITLE
Having trouble with sample "TypeError: task(...).finally is not a function"

### ISSUE THREAD

**Issue by ookimaki** [uniqys/UniqysKit-preview#2]
### Type
bug report

### Description
Hi I just follow the tutorial
https://medium.com/uniqys/uniqys-kit-preview-c806e5918b98

$ git colone git@github.com:uniqys/UniqysKit-preview.git
$ cd UniqysKit-preview
$ npm install
$ npm run bootstrap
$ npm run build
$ cd packages/samples/messages 
$ npm start

Then having trouble with npm start. It shows following error.

@uniqys/sample-messages@0.0.1 start /Users/taiju/.Trash/UniqysKit-preview/packages/samples/UniqysKit-preview/packages/samples/messages
> DEBUG=chain-core*,easy*,app* ts-node server/src/serve.ts

  chain-core:core start local core 38e7a8d69e9bef96fdd27cfe642f43fa0c3fcaf8 +0ms
TypeError: task(...).finally is not a function
    at semaphore.take (/Users/taiju/.Trash/UniqysKit-preview/packages/samples/UniqysKit-preview/packages/semaphore-async/dist/index.js:4:80)
    at Object.item.task (/Users/taiju/.Trash/UniqysKit-preview/packages/samples/UniqysKit-preview/node_modules/semaphore/lib/semaphore.js:40:29)
    at Object.take (/Users/taiju/.Trash/UniqysKit-preview/packages/samples/UniqysKit-preview/node_modules/semaphore/lib/semaphore.js:51:9)
    at Promise (/Users/taiju/.Trash/UniqysKit-preview/packages/samples/UniqysKit-preview/packages/semaphore-async/dist/index.js:4:55)
    at new Promise (<anonymous>)
    at Object.takeSemaphoreAsync (/Users/taiju/.Trash/UniqysKit-preview/packages/samples/UniqysKit-preview/packages/semaphore-async/dist/index.js:4:12)
    at BlockStore.lock (/Users/taiju/.Trash/UniqysKit-preview/packages/samples/UniqysKit-preview/packages/blockchain/dist/block-store.js:40:34)
    at Blockchain.ready (/Users/taiju/.Trash/UniqysKit-preview/packages/samples/UniqysKit-preview/packages/blockchain/dist/blockchain.js:14:31)
    at Local.initialize (/Users/taiju/.Trash/UniqysKit-preview/packages/samples/UniqysKit-preview/packages/chain-core-dev/dist/index.js:45:29)
    at Local.start (/Users/taiju/.Trash/UniqysKit-preview/packages/samples/UniqysKit-preview/packages/chain-core-dev/dist/index.js:28:20)

**Comment by koropicot** [comment]
Hi @ookimaki,

We check the issue, and found that this error appears when using the version 9 or earlier of Node.
Use the version 10 or later if this is the case.
https://node.green/#ES2018-features-Promise-prototype-finally

To manage versions, we recommend to use `ndenv`.
https://github.com/uniqys/UniqysKit-preview#setup-for-ndenv

And, as the tutorial missed this information, I added it.
Thanks to your report!
