### ISSUE TITLE
Internal Serever Error when accessing localhost:8080

### ISSUE THREAD

**Issue by ryokomy** [uniqys/UniqysKit-preview#3]
### Type

bug report

### Description
`npm start` seems to work well
```
> @uniqys/sample-messages@0.0.4 start /Users/ryokomy/src/github.com/uniqys/UniqysKit-preview/packages/samples/messages
> DEBUG=chain-core*,easy*,app* ts-node server/src/serve.ts

  chain-core:core start local core 38e7a8d69e9bef96fdd27cfe642f43fa0c3fcaf8 +0ms
  chain-core:core initialized at block(0) +5ms
  chain-core:core make consensus +1ms
  chain-core:core execute transaction in block(1) +2ms
  chain-core:core add block(1): 80597337033974deb25cd008c89ab924ae6c2bb1ebf69eb145bfbc2ecef4b750 +0ms
  chain-core:core need appState proof block +2ms
  chain-core:core propose block(2): 9b0abc0cc4e8ec16de7826a9e4a8c1177497f961feab2b1ebbdb3d624a656eb7 +1ms
  chain-core:core make consensus +0ms
  chain-core:core execute transaction in block(2) +0ms
  chain-core:core add block(2): 9b0abc0cc4e8ec16de7826a9e4a8c1177497f961feab2b1ebbdb3d624a656eb7 +0ms
```
but, after accessing localhost:8080, the word 'Internal Server Error' is displayed on the web browser.
The error message on terminal is the following.
```
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
      at ClientRequest.once (events.js:288:11)
      at new ClientRequest (_http_client.js:141:10)
      at Object.request (http.js:41:10)
      at Promise (/Users/ryokomy/src/github.com/uniqys/UniqysKit-preview/packages/easy-framework/dist/gateway.js:40:44)
      at new Promise (<anonymous>)
      at state.rwLock.readLock.use (/Users/ryokomy/src/github.com/uniqys/UniqysKit-preview/packages/easy-framework/dist/gateway.js:39:52)
      at lock.unlock (/Users/ryokomy/src/github.com/uniqys/UniqysKit-preview/packages/lock/dist/index.js:55:69)
      at process.nextTick (/Users/ryokomy/src/github.com/uniqys/UniqysKit-preview/packages/lock/dist/index.js:41:36)
      at process._tickCallback (internal/process/next_tick.js:61:11)
```

### Environment
- OS
macOS High Sierra, version 10.13.6
- browser
Google Chrome, Version 68.0.3440.106 (Official Build) (64-bit)
- npm
version 6.1.0
- node
v10.2.1

**Comment by koropicot** [comment]
Hi @ryokomy,

Thank you for reporting with detailed information.

This error is occered with Node.js v10.8 or earlier.
It's because the `http.request()` has be used in a new format of v10.9 and later.
https://nodejs.org/api/http.html#http_http_request_url_options_callback

So, to use v10.9 (or later) will probably solve your issue.

P.S.
We recommend to use ndenv for manage Node.js versions.
But the version written on the readme is old at this time :sweat_smile:.
I will fix it!
https://github.com/uniqys/UniqysKit-preview#setup-for-ndenv

**Comment by ryokomy** [comment]
@koropicot 
Thanks for your reply.
I confirmed it worked well with Node.js v10.11.0.
